/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.tugas_1_pbo_nomor1;

/**
 *
 * @author Marshya N
 */
public class Tugas_1_PBO_nomor1 {

    public static void main(String[] args) {
        String greeting = "Welcome to Core Java!";
        System.out.println(greeting);
        for (int i=0; i<greeting.length(); i++)
            System.out.print("=");
        System.out.println();
    }
}
